.pragma library

var FONT_DEFAULT_SIZE = 24; // DEPRECATED

var FONT_XXLARGE = 38;
var FONT_XLARGE  = 32;
var FONT_LARGE   = 28;
var FONT_SLARGE  = 26;
var FONT_DEFAULT = 24;
var FONT_LSMALL  = 22;
var FONT_SMALL   = 20;
var FONT_XSMALL  = 18;
var FONT_XXSMALL = 16;

var COLOR_FOREGROUND = "black"; // Text color
var COLOR_FOREGROUND_LIGHT = "white"
var COLOR_SECONDARY_FOREGROUND = "#888"; // Secondary text
var COLOR_SECONDARY_FOREGROUND_LIGHT = "#ddd"; // Secondary text
var COLOR_UNCONSPLCUOUS = "#ccc"

var SIZE_AVATAR_DEFAULT = 60;

var SIZE_ICON_DEFAULT = 32;
var SIZE_ICON_LARGE = 48;

var CORNER_MARGINS = 22;

var MARGIN_DEFAULT = 10;
var MARGIN_XLARGE = 16;

var PADDING_XSMALL  = 2;
var PADDING_SMALL   = 4;
var PADDING_MEDIUM  = 6;
var PADDING_LARGE   = 8;
var PADDING_DOUBLE  = 12;
var PADDING_XLARGE  = 16;
var PADDING_XXLARGE = 24;

var SPACING_DEFAULT = 10;
var SPACING_LARGE = 20

var HEIGHT_LIST_ITEM = 80;
var HEIGHT_TOOLBAR = 72;
var HEIGHT_HEADERBAR = 72
